NDefines.NCountry.CORRUPTION_FROM_BANNERS = 2
NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = -0.05
NDefines.NMilitary.BANNER_MANPOWER_USAGE = 0
NDefines.NMilitary.BANNER_REINFORCE_SPEED = 0.25
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 3.5
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 0
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 0.1
NDefines.NMilitary.BANNER_USES_CONSTRUCTION = 0



NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 75
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 15
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0

NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 4
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -25
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 60
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 35
NDefines.NCountry.PS_NAVAL_BARRAGE = 35
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.MINIMUM_POLICY_TIME = 5

NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 50
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0


NDefines.NEconomy.CARAVAN_FACTOR = 3
NDefines.NEconomy.CARAVAN_POWER_MAX = 25
NDefines.NEconomy.CARAVAN_POWER_MIN = 2
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 20
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30

NDefines.NEconomy.AUTONOMY_CHANGE_DURATION = 5475

NDefines.NMilitary.WARGOAL_MAX_BONUS = 35
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.7
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40
NDefines.NMilitary.MERCENARY_COMPANY_BUILDING_TIME = 0.4

NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 4

NDefines.NReligion.MAX_CHURCH_POWER = 300
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 20
NDefines.NReligion.STARTING_HARMONY = 50.0
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 2.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -5.0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.05
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0

NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.1
NDefines.NGovernment.COSSACKS_ABILITY_COSSACKS_SPAWN_SIZE = 0.1

